package com.pluralsight.cxfdemo.orders;

import javax.jws.WebService;

import org.springframework.beans.factory.annotation.Autowired;

import com.pluralsight.schema.order.AccountType;
import com.pluralsight.schema.order.ObjectFactory;
import com.pluralsight.schema.order.OrderInquiryResponseType;
import com.pluralsight.schema.order.OrderInquiryType;
import com.pluralsight.service.orders.Orders;

/**
 * This is the default implementation of the Orders interface generated by the
 * Maven CXF code-gen plugin. The class is annotated with the JAX-WS web service
 * annotation. The values for the port name and service name come from the
 * service and port WSDL elements. The endpoint interface value is the fully
 * qualified name for the Orders interface.
 * 
 * @author Michael Hoffman, Pluralsight
 * 
 */
@WebService(portName = "OrdersSOAP", serviceName = "Orders",
      endpointInterface = "com.pluralsight.service.orders.Orders",
      targetNamespace = "http://www.pluralsight.com/service/Orders/")
public class DefaultOrdersEndpoint implements Orders {

   @Override
   public OrderInquiryResponseType processOrderPlacement(
         OrderInquiryType orderInquiry) {

      ObjectFactory factory = new ObjectFactory();
      OrderInquiryResponseType response = factory.createOrderInquiryResponseType();
      AccountType account = factory.createAccountType();
      account.setAccountId(1);
      response.setAccount(account);
      return response;
   }

}
